-- Script de Inicialización Profesional para Monitoreo - Oracle 19c
ALTER SESSION SET CONTAINER = ORCLPDB1;

-- 1. Esquema de la Aplicación (RH-UAEMEX)
CREATE USER "RH-UAEMEX" IDENTIFIED BY "rh_pass_123" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO "RH-UAEMEX";

CREATE TABLE "RH-UAEMEX".empleados (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    puesto VARCHAR2(100),
    fecha_ingreso TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO "RH-UAEMEX".empleados (nombre, puesto) VALUES ('JUAN PEREZ', 'DESARROLLADOR');

-- 2. Usuario de Monitoreo SGIR (Perfil SRE)
CREATE USER monitor_user IDENTIFIED BY "monitor_pass" DEFAULT TABLESPACE USERS;
GRANT CREATE SESSION TO monitor_user;

-- Permisos de Diccionario: Permite ver DBA_TABLESPACES, DBA_OBJECTS, DBA_DATA_FILES, etc.
GRANT SELECT ANY DICTIONARY TO monitor_user;

-- Rol de Catálogo: Permite ver TODAS las vistas de rendimiento dinámico (V$SESSION, V$PDBS, V$RECOVERY_FILE_DEST)
GRANT SELECT_CATALOG_ROLE TO monitor_user;

-- Permisos explícitos sobre vistas críticas (redundancia de seguridad)
GRANT SELECT ON V_$SESSION TO monitor_user;
GRANT SELECT ON V_$INSTANCE TO monitor_user;
GRANT SELECT ON V_$PDBS TO monitor_user;

COMMIT;
