services:
  db:
    image: postgres:16-alpine
    container_name: sgir_postgres
    restart: always
    environment:
      - POSTGRES_USER=sgir
      - POSTGRES_PASSWORD=sgir
      - POSTGRES_DB=sgir_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./documentacion/01_modelo_fisico.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./documentacion/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql 
      - ./documentacion/03_seed_contenedores.sql:/docker-entrypoint-initdb.d/03_seed_contenedores.sql 

  mysql5:
    image: mysql:5.7
    container_name: sgir_mysql5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=sgir
      - MYSQL_DATABASE=sgir_db_5
      - MYSQL_USER=sgir
      - MYSQL_PASSWORD=sgir
    ports:
      - "3305:3306"
    volumes:
      - ./monitoreo/mysql5/01_usuario_mysql5.sql:/docker-entrypoint-initdb.d/init.sql

  mysql8:
    image: mysql:8.0
    container_name: sgir_mysql8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=sgir
      - MYSQL_DATABASE=sgir_db_8
      - MYSQL_USER=sgir
      - MYSQL_PASSWORD=sgir
    ports:
      - "3308:3306"
    volumes:
      - ./monitoreo/mysql8/01_usuario_mysql8.sql:/docker-entrypoint-initdb.d/01_usuario.sql
     # - ./monitoreo-mysql-8/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Esto por que consume mucho 
  #oracle19c:
  #  image: doctorkirk/oracle-19c
  #  container_name: sgir_oracle19c
  #  restart: always
  #  environment:
  #    - ORACLE_SID=ORCLCDB
  #    - ORACLE_PWD=sgir
  #    - ORACLE_CHARACTERSET=AL32UTF8
  #  ports:
  #    - "1521:1521"
  #  volumes:
  #    - oracle_data:/opt/oracle/oradata
  #    - ./monitoreo-oracle/init.sql:/opt/oracle/scripts/setup/01_init.sql

  mongodb:
    image: mongo:latest
    container_name: sgir_mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sgir
      - MONGO_INITDB_ROOT_PASSWORD=sgir
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27017:27017"
    volumes:
     # - ./monitoreo-mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./monitoreo/mongodb/01_usuario.js:/docker-entrypoint-initdb.d/01_usuario.js:ro
  # ==========================================
  # SERVIDOR SSH PARA PRUEBAS DE MONITOREO
  # ==========================================
  ssh_server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: sgir_ssh_server
    restart: always
    environment:
      - USER_NAME=sgir_user
      - USER_PASSWORD=sgir_pass
      - PASSWORD_ACCESS=true
    ports:
      - "2222:2222"
  fedora_node:
    image: fedora:latest
    container_name: sgir_fedora
    restart: always
    tty: true
    stdin_open: true
    environment:
      - USER_NAME=sgir
      - USER_PASSWORD=sgir
      - DB_USER=sgir
      - DB_PASSWORD=sgir
    volumes:
      - ./monitoreo/fedoraOS/init.sh:/usr/local/bin/init.sh:ro
    entrypoint: ["/bin/bash", "/usr/local/bin/init.sh"]
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "2223:22"
    networks:
      - default

volumes:
  postgres_data:
  #oracle_data:
